apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: default

spec: 
  ports:
  - nodePort: 30555
    port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: nginx

  type: LoadBalancer